version: '3.4'

services:
  conta:
    image: conta
    build:
      context: .
      dockerfile: cont_a/Dockerfile
    networks:
      - test_network
    ports:
      - '5000'
    expose:
      - '5000'
    volumes:
      - shared:/shared:consistent

  contb:
    depends_on:
      - conta
    image: contb
    build:
      context: .
      dockerfile: cont_b/Dockerfile
    networks:
      - test_network
    volumes:
      - shared:/shared:consistent

networks:
  test_network:
    driver: bridge
volumes:
  shared:
    external: true